### ISSUE TITLE
Multiple qr code scanning at once

### ISSUE THREAD

**Issue by rutvikrockers** [Dynamsoft/react-native-dbr#23]
Multiple qr code scan at same time not working. Can you please help me?

**Comment by zyunique** [comment]
Replace the same function in the “Demo->BarcodeReaderManagerViewController.m” with the following code ：

-(void) onReadImageBufferComplete:(NSArray *) readResult{
    if(readResult == nil || dbrManager.isPauseFramesComing == YES)
    {
        dbrManager.isCurrentFrameDecodeFinished = YES;
        return;
    }
    double timeInterval = [dbrManager.startRecognitionDate timeIntervalSinceNow] * -1;
    double left = FLT_MAX;
    double top = FLT_MAX;
    double right = 0;
    double bottom = 0;
    NSString* msgText = @"";
    if (readResult.count == 0) {
        dbrManager.isCurrentFrameDecodeFinished = YES;
        return;
    } else {
        for (NSInteger i=0; i<[readResult count]; i++) {
            for (int j = 0; j < ((iTextResult*)readResult[i]).localizationResult.resultPoints.count; ++j) {
                left = left < [((iTextResult*)readResult[i]).localizationResult.resultPoints[j] CGPointValue].x ? left : [((iTextResult*)readResult[i]).localizationResult.resultPoints[j] CGPointValue].x;
                top = top < [((iTextResult*)readResult[i]).localizationResult.resultPoints[j] CGPointValue].y ? top : [((iTextResult*)readResult[i]).localizationResult.resultPoints[j] CGPointValue].y;
                right = right > [((iTextResult*)readResult[i]).localizationResult.resultPoints[j] CGPointValue].x ? right : [((iTextResult*)readResult[i]).localizationResult.resultPoints[j] CGPointValue].x;
                bottom = bottom > [((iTextResult*)readResult[i]).localizationResult.resultPoints[j] CGPointValue].y ? bottom : [((iTextResult*)readResult[i]).localizationResult.resultPoints[j] CGPointValue].y;
            }
            
            if (((iTextResult*)readResult[i]).barcodeFormat_2 != 0)
            {
                msgText = [msgText stringByAppendingString:[NSString stringWithFormat:@"\nType: %@\n\nValue: %@\n\nRegion: {Left: %.f, Top: %.f, Right: %.f, Bottom: %.f}\n\nInterval: %.03f seconds\n\n", ((iTextResult*)readResult[i]).barcodeFormatString_2, ((iTextResult*)readResult[i]).barcodeText, left, top, right, bottom, timeInterval]];
            } else {
                msgText = [msgText stringByAppendingString:[NSString stringWithFormat:@"\nType: %@\n\nValue: %@\n\nRegion: {Left: %.f, Top: %.f, Right: %.f, Bottom: %.f}\n\nInterval: %.03f seconds\n\n", ((iTextResult*)readResult[i]).barcodeFormatString, ((iTextResult*)readResult[i]).barcodeText, left, top, right, bottom, timeInterval]];
            }
        }
    }
    
    dispatch_async(dispatch_get_main_queue(), ^{
        [[NSNotificationCenter defaultCenter]postNotificationName:@"callback" object:nil userInfo:@{@"result": msgText}];
    });
}

**Comment by zyunique** [comment]
> Multiple qr code scan at same time not working. Can you please help me?

Replace the same function in the “Demo->BarcodeReaderManagerViewController.m” with the following code ：

-(void) onReadImageBufferComplete:(NSArray ) readResult{
if(readResult == nil || dbrManager.isPauseFramesComing == YES)
{
dbrManager.isCurrentFrameDecodeFinished = YES;
return;
}
double timeInterval = [dbrManager.startRecognitionDate timeIntervalSinceNow] * -1;
double left = FLT_MAX;
double top = FLT_MAX;
double right = 0;
double bottom = 0;
NSString msgText = @"";
if (readResult.count == 0) {
dbrManager.isCurrentFrameDecodeFinished = YES;
return;
} else {
for (NSInteger i=0; i<[readResult count]; i++) {
for (int j = 0; j < ((iTextResult*)readResult[i]).localizationResult.resultPoints.count; ++j) {
left = left < [((iTextResult*)readResult[i]).localizationResult.resultPoints[j] CGPointValue].x ? left : [((iTextResult*)readResult[i]).localizationResult.resultPoints[j] CGPointValue].x;
top = top < [((iTextResult*)readResult[i]).localizationResult.resultPoints[j] CGPointValue].y ? top : [((iTextResult*)readResult[i]).localizationResult.resultPoints[j] CGPointValue].y;
right = right > [((iTextResult*)readResult[i]).localizationResult.resultPoints[j] CGPointValue].x ? right : [((iTextResult*)readResult[i]).localizationResult.resultPoints[j] CGPointValue].x;
bottom = bottom > [((iTextResult*)readResult[i]).localizationResult.resultPoints[j] CGPointValue].y ? bottom : [((iTextResult*)readResult[i]).localizationResult.resultPoints[j] CGPointValue].y;
}

        if (((iTextResult*)readResult[i]).barcodeFormat_2 != 0)
        {
            msgText = [msgText stringByAppendingString:[NSString stringWithFormat:@"\nType: %@\n\nValue: %@\n\nRegion: {Left: %.f, Top: %.f, Right: %.f, Bottom: %.f}\n\nInterval: %.03f seconds\n\n", ((iTextResult*)readResult[i]).barcodeFormatString_2, ((iTextResult*)readResult[i]).barcodeText, left, top, right, bottom, timeInterval]];
        } else {
            msgText = [msgText stringByAppendingString:[NSString stringWithFormat:@"\nType: %@\n\nValue: %@\n\nRegion: {Left: %.f, Top: %.f, Right: %.f, Bottom: %.f}\n\nInterval: %.03f seconds\n\n", ((iTextResult*)readResult[i]).barcodeFormatString, ((iTextResult*)readResult[i]).barcodeText, left, top, right, bottom, timeInterval]];
        }
    }
}

dispatch_async(dispatch_get_main_queue(), ^{
    [[NSNotificationCenter defaultCenter]postNotificationName:@"callback" object:nil userInfo:@{@"result": msgText}];
});
}

**Comment by rutvikrockers** [comment]
thanks for the iOS controller code. I will get back to you after successfully implementing this code. I find this error when I click on **Read Barcode** Button in the android device. And what is the code for android for multiple QR code scan?
![Screenshot_20200416-104335](https://user-images.githubusercontent.com/31954734/79418026-35756580-7fd1-11ea-9732-708ba296c417.jpg)

**Comment by zyunique** [comment]
> thanks for the iOS controller code. I will get back to you after successfully implementing this code. I find this error when I click on **Read Barcode** Button in the android device. And what is the code for android for multiple QR code scan?
> ![Screenshot_20200416-104335](https://user-images.githubusercontent.com/31954734/79418026-35756580-7fd1-11ea-9732-708ba296c417.jpg)

make sure App.js use the //android code. And android is already available for multiple QR code scan.
onButtonPress = () => {
	    //android
	    BarcodeReaderManager.readBarcode('your license here',events => {
  	      this.setState({result: events});
  	    },err => {
  	      alert(err);
  	    }
	    );
  	}

**Comment by rutvikrockers** [comment]
hello,
 I used the android part code and for now, disable the iOS part code on the button click. I am getting the below error where the application crashed on the button click.
[20200416-183428-720x1280.zip](https://github.com/dynamsoft-dbr/react-native-dbr/files/4487392/20200416-183428-720x1280.zip)
