### ISSUE TITLE
Android App crashed

### ISSUE THREAD

**Issue by rutvikrockers** [Dynamsoft/react-native-dbr#24]
hello,
I used the android part code and for now. I am getting the below error where the application crashed on the button click.
20200416-183428-720x1280.zip

**Comment by zyunique** [comment]
> hello,
> I used the android part code and for now. I am getting the below error where the application crashed on the button click.
> 20200416-183428-720x1280.zip

what android device do you use? Simulator or real machine?

**Comment by zyunique** [comment]
> hello,
> I used the android part code and for now. I am getting the below error where the application crashed on the button click.
> 20200416-183428-720x1280.zip

Different APIs will have different problems

**Comment by rutvikrockers** [comment]
I am using a real device one plus 5. Every time I clicked on button **view barcode**  and app is going to crash. Is there any solution for this or working code, please. I really need this code for multiple scans.

**Comment by zyunique** [comment]
> I am using a real device one plus 5. Every time I clicked on button **view barcode** and app is going to crash. Is there any solution for this or working code, please. I really need this code for multiple scans.

what is your android api version ？android 7.0 or 8.0 ？

**Comment by zyunique** [comment]
> I am using a real device one plus 5. Every time I clicked on button **view barcode** and app is going to crash. Is there any solution for this or working code, please. I really need this code for multiple scans.

any debug logs when app is going to crash

any debug log

**Comment by rutvikrockers** [comment]
The API version is 9.0. I tried to console and figure out what is the error but no logs at all.

**Comment by zyunique** [comment]
> The API version is 9.0. I tried to console and figure out what is the error but no logs at all.

reload app : 
1. rm -rf node_modules 
2. yarn
3. react-native run-android

**Comment by zyunique** [comment]
> The API version is 9.0. I tried to console and figure out what is the error but no logs at all.

**Comment by zyunique** [comment]
> The API version is 9.0. I tried to console and figure out what is the error but no logs at all.

does the above method work?

**Comment by rutvikrockers** [comment]
I did exactly the same process as per above but still, it gets crash

**Comment by zyunique** [comment]
> I did exactly the same process as per above but still, it gets crash

activity_main.xml:
1. line 7 -> tools:context="com.demo.camera.DBR
2. line 45 -> com.demo.camera.RectLayer

**Comment by zyunique** [comment]
> I did exactly the same process as per above but still, it gets crash

almost this bug causes a crash

**Comment by rutvikrockers** [comment]
so what should be the solution?

**Comment by zyunique** [comment]
> so what should be the solution?

firstly, react-native-dbr/androidLib/src/main/res/layout/activity_main.xml : 
1.line 7 : tools:context="com.dynamsoft.camera.DBR" -> tools:context="com.demo.camera.DBR"
2.line 45:  com.dynamsoft.camera.RectLayer -> com.demo.camera.RectLayer
and then,
1.rm -rf node_modules
2.yarn
3.react-native run-android

**Comment by rutvikrockers** [comment]
Hello,
this trick worked like a charm. but it only detects single Barcode or QR Code and I need multiple Scan at once. Meaning more than two or three QR codes able to scan in one frame.is it possible in this code? right now it only scans one QR code. Thanks a lot for your help but is it possible for multi QR codes scan at once?
[20200421-123338-480x852.zip](https://github.com/dynamsoft-dbr/react-native-dbr/files/4508245/20200421-123338-480x852.zip)

**Comment by zyunique** [comment]
> Hello,
> this trick worked like a charm. but it only detects single Barcode or QR Code and I need multiple Scan at once. Meaning more than two or three QR codes able to scan in one frame.is it possible in this code? right now it only scans one QR code. Thanks a lot for your help but is it possible for multi QR codes scan at once?
> [20200421-123338-480x852.zip](https://github.com/dynamsoft-dbr/react-native-dbr/files/4508245/20200421-123338-480x852.zip)

replace the file here : androidLib/src/main/java/com/demo/camera/DBR.java
[DBR.java.zip](https://github.com/dynamsoft-dbr/react-native-dbr/files/4508658/DBR.java.zip)

then 
rm -rf node_modules
yarn
react-native run-android

**Comment by rutvikrockers** [comment]
I got this error in DBR.java file:
error: cannot find symbol
settings.barcodeFormatIds_2 = EnumBarcodeFormat_2.BF2_POSTALCODE | EnumBarcodeFormat_2.BF2_NONSTANDARD_BARCODE | EnumBarcodeFormat_2.BF2_DOTCODE;                                                                                                                                                  symbol:   variable BF2_DOTCODE
location: class EnumBarcodeFormat_2
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

**Comment by zyunique** [comment]
> I got this error in DBR.java file:
> error: cannot find symbol
> settings.barcodeFormatIds_2 = EnumBarcodeFormat_2.BF2_POSTALCODE | EnumBarcodeFormat_2.BF2_NONSTANDARD_BARCODE | EnumBarcodeFormat_2.BF2_DOTCODE; symbol: variable BF2_DOTCODE
> location: class EnumBarcodeFormat_2
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> 1 error
> 
> FAILURE: Build failed with an exception.

Just need to modify some rows in androidLib/src/main/java/com/demo/camera/DBR.java
then:
rm -rf node_modules
yarn
react-native run-android
[截屏2020-04-21 17.48.49.zip](https://github.com/dynamsoft-dbr/react-native-dbr/files/4509143/2020-04-21.17.48.49.zip)

**Comment by rutvikrockers** [comment]
I changed as per your description but I m getting errors while react-native run-android command. I did check twice my code but after the file change DBR.java. project is not running. Seriously DBR.java File is not perfect.

**Comment by zyunique** [comment]
> I changed as per your description but I m getting errors while react-native run-android command. I did check twice my code but after the file change DBR.java. project is not running. Seriously DBR.java File is not perfect.

make sure the file :androidLib/lib/DynamsoftBarcodeReader.aar is up to date
[截屏2020-04-22 14.06.32.zip](https://github.com/dynamsoft-dbr/react-native-dbr/files/4514093/2020-04-22.14.06.32.zip)

**Comment by zyunique** [comment]
> I changed as per your description but I m getting errors while react-native run-android command. I did check twice my code but after the file change DBR.java. project is not running. Seriously DBR.java File is not perfect.

version 7.4.0 just updated a few days ago，variable BF2_DOTCODE in DBR.java cannot be found in old aar

**Comment by rutvikrockers** [comment]
works like a charm. I want to open the scanner immediately after the launch screen. Not on button click.
So I need to set like this in return() :
**<BarcodeReaderManager> <BarcodeReaderManager />**
But I don't know the properties of this scanner. So is it possible to set Barcode code in return
view and get the results?

**Comment by zyunique** [comment]
> works like a charm. I want to open the scanner immediately after the launch screen. Not on button click.
> So I need to set like this in return() :
> ** **
> But I don't know the properties of this scanner. So is it possible to set Barcode code in return
> view and get the results?

[app&package.zip](https://github.com/dynamsoft-dbr/react-native-dbr/files/4520399/app.package.zip)
replace app.js & package.json ,
rm -rf node_modules
yarn
react-native run-android

**Comment by zyunique** [comment]
> works like a charm. I want to open the scanner immediately after the launch screen. Not on button click.
> So I need to set like this in return() :
> ** **
> But I don't know the properties of this scanner. So is it possible to set Barcode code in return
> view and get the results?

does this method work?

**Comment by rutvikrockers** [comment]
yes, thanks a lot. works great.
