### ISSUE TITLE
iOS App not launching from xCode

### ISSUE THREAD

**Issue by rutvikrockers** [Dynamsoft/react-native-dbr#29]
hello,
can you please give me running iOS part code. I have so many errors while launching the app from Xcode. I need it in urgent.

**Comment by zyunique** [comment]
> hello,
> can you please give me running iOS part code. I have so many errors while launching the app from Xcode. I need it in urgent.

ok, I will check the code as soon as possible

**Comment by zyunique** [comment]
> hello,
> can you please give me running iOS part code. I have so many errors while launching the app from Xcode. I need it in urgent.

show me errors

**Comment by rutvikrockers** [comment]
it says, 
ld: warning: Could not find or use auto-linked framework 'DynamsoftBarcodeReader'
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_DynamsoftBarcodeReader", referenced from:
      objc-class-ref in libBarcodeReaderManager.a(DbrManager.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by zyunique** [comment]
> x86_64

clean project.
Need to run on a real machine

**Comment by zyunique** [comment]
> it says,
> ld: warning: Could not find or use auto-linked framework 'DynamsoftBarcodeReader'
> Undefined symbols for architecture x86_64:
> "_OBJC_CLASS_$_DynamsoftBarcodeReader", referenced from:
> objc-class-ref in libBarcodeReaderManager.a(DbrManager.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

clean project.
Need to run on a real machine
