### ISSUE TITLE
Archive File Generate issue

### ISSUE THREAD

**Issue by rutvikrockers** [Dynamsoft/react-native-dbr#33]
i got errors of not found symbol while creating archive build.can you please help me with this.
![Screenshot 2020-05-20 at 12 46 32 PM](https://user-images.githubusercontent.com/31954734/82416752-30a44580-9a98-11ea-9968-0288c679f0e2.png)

**Comment by zyunique** [comment]
check build settings->framework search path has $(PROJECT_DIR)/../Libraries
